[package]
disabled = true

[aws]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Arch = " "
EndeavourOS = " "
Linux = " "
Macos = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[status]
symbol = " "

[zig]
symbol = " "
